### ISSUE TITLE
Feature-Request: E-Mail mit Inserttag

### ISSUE THREAD

**Issue by ngdot** [cliffparnitzky/TinyMceLinkAutoDetect#1]
Hi,

wie wäre es wenn die E-Mail-Adresse automatisch in das Contao Inserttag {{email::*}} gesetzt wird,
dadurch wäre die E-Mail-Adresse zusätzlich verschlüsselt.

Nico

**Comment by cliffparnitzky** [comment]
Contao Standard Verhalten ist, dass beim parsen der Seite, E-Mail Links automatisch verschlüsselt ausgeben werden. Getestet unter Contao 3.3.7 sowie Contao 3.5.0.

Insofern wäre sowas nicht nötig.

**Comment by ngdot** [comment]
Okay, wusste ich nicht, danke für die Aufklärung!
Erweiterung läuft super, danke dafür :)

**Comment by cliffparnitzky** [comment]
Top, dann mach ich das hier zu.
